version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/bnema/gio-shadcn
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  revive:
    min-confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  
  staticcheck:
  
  unused:
  
  gosimple:
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow
      - unnamedResult
      - unnecessaryBlock

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - misspell
    - unconvert
    - unparam
    - gosec
    - asciicheck
    - prealloc
    - predeclared
    - makezero
    - goconst
    - godot
    - gocyclo
    - dupl
    - gomodguard
    - whitespace

formatters:
  disable-all: true
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  exclude:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude known linters from partially hard-to-fix issues
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude linters in vendor directories
    - path: vendor/
      linters:
        - gofmt
        - goimports
        - govet
        - revive
        - gocritic
        - misspell
        - unconvert
        - unparam
        - gosec
        - asciicheck
        - prealloc
        - predeclared
        - makezero
        - goconst
        - godot
        - gocyclo
        - dupl
        - gomodguard
        - exportloopref
        - whitespace
  
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    # Disable some linters for generated files
    - path: ".*\\.pb\\.go"
      linters:
        - gofmt
        - goimports
        - govet
        - revive
        - gocritic
        - misspell
        - unconvert
        - unparam
        - gosec
        - asciicheck
        - prealloc
        - predeclared
        - makezero
        - goconst
        - godot
        - gocyclo
        - dupl
        - gomodguard
        - exportloopref
        - whitespace
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false